extends Resource

@export var VAR_NAMES: Dictionary[ATTRIBUTE_ENUMS.TYPE, String]

#
#@export var VAR_NAMES: Dictionary[ATTRIBUTE_ENUMS.TYPE, String]= {
	#ATTRIBUTE_ENUMS.TYPE.MAX_HP: "max_hp",
	#ATTRIBUTE_ENUMS.TYPE.HP: "hp",
	#ATTRIBUTE_ENUMS.TYPE.MAX_MP: "max_mp",
	#ATTRIBUTE_ENUMS.TYPE.MP: "mp",
	#ATTRIBUTE_ENUMS.TYPE.ARMOR: "armor",
	#ATTRIBUTE_ENUMS.TYPE.MOVEMENT_SPEED: "movement_speed",
	#ATTRIBUTE_ENUMS.TYPE.ATTACK_SPEED_MULTIPLIER: "attack_speed_multiplier",
	#ATTRIBUTE_ENUMS.TYPE.MAGIC_DAMAGE_MULTUPLIER: "magic_multiplier",
	#ATTRIBUTE_ENUMS.TYPE.PHYSICAL_DAMAGE_MULTIPLIER: "physical_multiplier",
	#ATTRIBUTE_ENUMS.TYPE.POISON_DAMAGE_MULTIPLIER: "poison_multiplier",
	#ATTRIBUTE_ENUMS.TYPE.PIERCE_DAMAGE_MULTIPLIER: "pierce_multiplier",
	#ATTRIBUTE_ENUMS.TYPE.BLEED_DAMAGE_MULTIPLIER: "bleed_multiplier",
	#ATTRIBUTE_ENUMS.TYPE.MAGIC_RESISTANCE: "magic_resistance",
	#ATTRIBUTE_ENUMS.TYPE.BLEED_RESISTANCE: "bleed_resistance",
	#ATTRIBUTE_ENUMS.TYPE.POISON_RESISTANCE: "poison_resistance",
	#ATTRIBUTE_ENUMS.TYPE.PIERCE_RESISTANCE: "pierce_resistance"
#}
