extends Resource

const Descriptor = preload("res://Resources/items/item_descriptor.gd")

const idle_asset_root = "res://Assets/character_sprites/walkcycle/"
const weapon_asset_roots: Dictionary[ITEM_ENUMS.WEAPON_TYPE, String] = {
	ITEM_ENUMS.WEAPON_TYPE.NONE: "",
	ITEM_ENUMS.WEAPON_TYPE.DAGGER: "res://Assets/character_sprites/dagger/",
	ITEM_ENUMS.WEAPON_TYPE.SPEAR: "res://Assets/character_sprites/spear/",
	ITEM_ENUMS.WEAPON_TYPE.BOW: "res://Assets/character_sprites/bow/"
}

#func generate_weapon_assets(asset_file: String) -> Dictionary[ITEM_ENUMS.WEAPON_TYPE, String]:
	#var res: Dictionary[ITEM_ENUMS.WEAPON_TYPE, String] = weapon_asset_roots.duplicate()
	#for key in res:
		#if res[key] != "":
			#res[key] += asset_file
		#else:
			#res[key] = ""
	#return res
#
#func generate_idle_asset(asset_file: String):
	#if (asset_file != ""):
		#return idle_asset_root + asset_file
	#else:
		#return ""


@export var ITEM_DESCRIPTIONS: Dictionary[ITEM_ENUMS.ITEM_LIST, Descriptor]
#var ITEM_DESCRIPTIONS: Dictionary[ITEM_ENUMS.ITEM_LIST, Descriptor] = {
	#ITEM_ENUMS.ITEM_LIST.NONE: Descriptor.new("nonamehere",
													#"thisisaninvaliditem",
													#ITEM_ENUMS.EQUIP_SLOTS.NONE,
													#0,
													#"",
													#generate_weapon_assets(""),
													#0, 0, 0, 0),
	##head
	#ITEM_ENUMS.ITEM_LIST.CLOTH_HEAD: Descriptor.new("Cloth Hood",
													#"Keeps the sun out of the eyes.",
													#ITEM_ENUMS.EQUIP_SLOTS.HEAD,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("HEAD_robe_hood.png"), 
													#generate_weapon_assets("HEAD_robe_hood.png"),
													#0, 5, 5, 0),
	#ITEM_ENUMS.ITEM_LIST.LEATHER_HEAD: Descriptor.new("Leather Hat",
													#"A leather hat. Looks like robin hood yet?",
													#ITEM_ENUMS.EQUIP_SLOTS.HEAD,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("HEAD_leather_armor_hat.png"), 
													#generate_weapon_assets("HEAD_leather_armor_hat.png"),
													#0, 5, 0, 1),
	#ITEM_ENUMS.ITEM_LIST.CHAINMAIL_HEAD: Descriptor.new("Chainmail Coif",
													#"A coif made of chainmail links.",
													#ITEM_ENUMS.EQUIP_SLOTS.HEAD,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("HEAD_chain_armor_hood.png"), 
													#generate_weapon_assets("HEAD_chain_armor_hood.png"),
													#0, 0, 0, 2),
	#ITEM_ENUMS.ITEM_LIST.PLATE_HEAD: Descriptor.new("Plate Helmet",
													#"Sturdy and reliable. A little heavy though..",
													#ITEM_ENUMS.EQUIP_SLOTS.HEAD,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("HEAD_plate_armor_helmet.png"), 
													#generate_weapon_assets("HEAD_plate_armor_helmet.png"),
													#5, -5, -5, 3),
	#ITEM_ENUMS.ITEM_LIST.LEATHER_SHOULDER: Descriptor.new("Leather Spaulders",
													#"Leather spaulder description.",
													#ITEM_ENUMS.EQUIP_SLOTS.SHOULDER,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("TORSO_leather_armor_shoulders.png"), 
													#generate_weapon_assets("TORSO_leather_armor_shoulders.png"),
													#0, 5, 0, 1),
	#ITEM_ENUMS.ITEM_LIST.PLATE_SHOULDER: Descriptor.new("Plate Shoulderguards",
													#"Good for stopping decapitation. Not so good for getting a good swing.",
													#ITEM_ENUMS.EQUIP_SLOTS.SHOULDER,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("TORSO_plate_armor_arms_shoulders.png"), 
													#generate_weapon_assets("TORSO_plate_armor_arms_shoulders.png"),
													#0, 0, -5, 3),
	#ITEM_ENUMS.ITEM_LIST.CLOTH_CHEST: Descriptor.new("Cloth Shirt",
													#"May as well be naked.",
													#ITEM_ENUMS.EQUIP_SLOTS.CHEST,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("TORSO_robe_shirt_brown.png"), 
													#generate_weapon_assets("TORSO_robe_shirt_brown.png"),
													#0, 10, 5, 0),
	#ITEM_ENUMS.ITEM_LIST.LEATHER_CHEST: Descriptor.new("Leather Armor",
													#"Reasonable protection I guess",
													#ITEM_ENUMS.EQUIP_SLOTS.CHEST,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("TORSO_leather_armor_torso.png"), 
													#generate_weapon_assets("TORSO_leather_armor_torso.png"),
													#0, 5, 1, 1),
	#ITEM_ENUMS.ITEM_LIST.CHAINMAIL_CHEST: Descriptor.new("Chainmail Armor",
													#"Like a silk dress, except its made of metal and not a dress",
													#ITEM_ENUMS.EQUIP_SLOTS.CHEST,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("TORSO_chain_armor_torso.png"), 
													#generate_weapon_assets("TORSO_chain_armor_torso.png"),
													#0, 0, 0, 3),
	#ITEM_ENUMS.ITEM_LIST.PLATE_CHEST: Descriptor.new("Plate Armor",
													#"Hard to move around when you're weighed down.",
													#ITEM_ENUMS.EQUIP_SLOTS.CHEST,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("TORSO_plate_armor_torso.png"), 
													#generate_weapon_assets("TORSO_plate_armor_torso.png"),
													#10, -10, -10, 5),
	#ITEM_ENUMS.ITEM_LIST.CLOTH_LEGS: Descriptor.new("Cloth Pants",
													#"Are you even wearing anything below the belt?",
													#ITEM_ENUMS.EQUIP_SLOTS.LEGS,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("LEGS_pants_greenish.png"), 
													#generate_weapon_assets("LEGS_pants_greenish.png"),
													#0, 10, 5, 0),
	#ITEM_ENUMS.ITEM_LIST.PLATE_LEGS: Descriptor.new("Plate Leg Guards",
													#"... might be a little difficult to run in these",
													#ITEM_ENUMS.EQUIP_SLOTS.LEGS,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("LEGS_plate_armor_pants.png"), 
													#generate_weapon_assets("LEGS_plate_armor_pants.png"),
													#10, -10, 0, 3),
	#ITEM_ENUMS.ITEM_LIST.CLOTH_BOOTS: Descriptor.new("Cloth Shoes",
													#"Comfy",
													#ITEM_ENUMS.EQUIP_SLOTS.BOOTS,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("FEET_shoes_brown.png"), 
													#generate_weapon_assets("FEET_shoes_brown.png"),
													#0, 10, 0, 0),
	#ITEM_ENUMS.ITEM_LIST.PLATE_BOOTS: Descriptor.new("Plate Grieves",
													#"Good protection from nails.",
													#ITEM_ENUMS.EQUIP_SLOTS.BOOTS,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("FEET_plate_armor_shoes.png"), 
													#generate_weapon_assets("FEET_plate_armor_shoes.png"),
													#5, 0, 0, 1),
	#ITEM_ENUMS.ITEM_LIST.PLATE_GLOVES: Descriptor.new("Plate Gauntlets",
													#"Won't bruise your knuckles with these",
													#ITEM_ENUMS.EQUIP_SLOTS.GLOVES,
													#ITEM_ENUMS.WEAPON_TYPE.NONE,
													#generate_idle_asset("HANDS_plate_armor_gloves.png"), 
													#generate_weapon_assets("HANDS_plate_armor_gloves.png"),
													#0, 0, 5, 1),
	#ITEM_ENUMS.ITEM_LIST.DAGGER: Descriptor.new("Dagger",
													#"Does a fast, short range sweeping attack",
													#ITEM_ENUMS.EQUIP_SLOTS.WEAPON,
													#ITEM_ENUMS.WEAPON_TYPE.DAGGER,
													#"", 
													#generate_weapon_assets("WEAPON_dagger.png"),
													#0, 0, 5, 0),
	#ITEM_ENUMS.ITEM_LIST.SPEAR: Descriptor.new("Spear",
													#"Average speed medium range frontal area attack.",
													#ITEM_ENUMS.EQUIP_SLOTS.WEAPON,
													#ITEM_ENUMS.WEAPON_TYPE.SPEAR,
													#"", 
													#generate_weapon_assets("WEAPON_spear.png"),
													#0, 0, 10, 0),
	#ITEM_ENUMS.ITEM_LIST.BOW: Descriptor.new("Bow",
													#"Shoots a long range projectile that can pierce up to 3 targets. Slow attack speed.",
													#ITEM_ENUMS.EQUIP_SLOTS.WEAPON,
													#ITEM_ENUMS.WEAPON_TYPE.BOW,
													#"", 
													#generate_weapon_assets("WEAPON_bow.png"),
													#0, 0, 20, 0)
#}
